# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - unsystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://undashboarddevregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc0f31bb9de14b5eaa02ef0b361dae8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6fe64f6cadbe479a8b739197a64f0107 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: undashboarddevregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bc0f31bb9de14b5eaa02ef0b361dae8e }}/unsystemmain:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'unsystem'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_243880cd1b514012a8de3fe65d39b35a }}
        images: 'undashboarddevregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bc0f31bb9de14b5eaa02ef0b361dae8e }}/unsystemmain:${{ github.sha }}'